export const SET_LANGUAGE_INDEX = 'SET_LANGUAGE_INDEX';
export const SET_PAGE_INDEX = 'SET_PAGE_INDEX';
export const SET_THEME_INDEX = 'SET_THEME_INDEX';
export const SET_THEME_COLOR_INDEX = 'SET_THEME_COLOR_INDEX';
export const SET_PAGE_BEFORE_LOGIN = 'SET_PAGE_BEFORE_LOGIN';
